### PR TITLE
ZigBee refactoring

### PR DESCRIPTION
**Pull request by timvandermeij**
This patch series is preparation work for the `RF_Sensor` refactoring. It includes:
- renaming XBee to RF sensor where possible;
- making Travis install all project dependencies for Pylint to detect all of them and not label them as missing imports;
- resolving all remaining Pylint issues.

### CODE REVIEW

**Comment by timvandermeij** [comment]
Travis now correctly detects that there was a cache for the branch, but there is none for the master branch or this PR and thus creates it. Nice!

**Comment by lhelwerd** [comment]
The one for master not yet displayed in the [list of caches](https://travis-ci.org/timvandermeij/mobile-radio-tomography/caches), but it will get created now that there is a push to master.

One minor thing about the dependency installation: Due to an additional argument after one of the `popd` commands in `travis.sh`, the script does not leave `~/lirc` correctly. Thus `sip` and `PyQt` are also extracted and compiled there. It does not matter for the cache since all of it is added there, but it is something we could fix for clarity.

**Comment by timvandermeij** [comment]
I'll push that fix after the cache for master is created. Thanks!

**Comment by timvandermeij** [comment]
I removed all old caches and built a fresh new cache for the master branch to solve this issue.

**Pull request merged**
