### PR TITLE
Settings manager

### PR DESCRIPTION
**Pull request by lhelwerd**
- Convert the `settings.json` to a dictionary of overrides only, and move the specification of defaults to `settings/defaults.json`. The XBee packet specifications now live in `zigbee/specifications.json`.
- Make use of more information about the settings, such as help text, possible options (possibly based on module attributes), an explicit type and other constraints, in `Arguments` and `Settings.set`.
- Add tests for new functionality in `Arguments` and `Settings`.
- Introduce a Settings view in the control panel, using a selectable list of components and lazily-loaded stacked settings panels. Each setting has its own widget with information about the setting and a type-specific form input. These form widgets range from textual input validation, to sliders and list/dictionary groups.
- A search filter allows quick access to specific settings, searching the available information.
- The Send button allows reviewing the changes. It currently only writes a `settings.json` with all non-default values to the ground station. We can later easily augment it with a settings packet sender similar to the Waypoints view.

This PR consists of two parts: the backend settings changes and the control panel Settings view. The first part can be reviewed by following the step-wise commits. The Settings view was more jumbled in earlier stages and is very large, so looking at the files or playing with the view (use `python2 control_panel.py --controller-xbee-simulation` if you do not have physical XBees) is a better way to review this part.

### CODE REVIEW

**Comment by timvandermeij** [comment]
Nice work! I have played around with it a bit and I pushed a commit that fixes a filtering issue.

For some reason the list input boxes (take for instance XBee sensor physical) are very small for me, so small that I can only see two characters of the total input. Do you have any idea what causes that? The width of other input fields is fine.

My new commit seems to have triggered one of the intermittent Travis CI issues by the way, but this time the output is more interesting: a KeyboardInterrupt?! It seems to happen when fetching the defaults JSON file, although I'm not entirely convinced that it's caused by this PR.

If you have an idea for the input box issue I can probably do a complete review tonight.

By the way, I'm currently working on understanding all aspects of the reconstruction problem and creating a detailed write-up of the problem and all reconstruction methods, hence the limited commit activity ;-)

**Comment by lhelwerd** [comment]
Perhaps you can also lowercase the help text in  `_match_setting` for better filtering there as well.

Do you mean the list on the left side or the inputs for the "sensors" setting? For me the former is always the same fixed size and the widget items always take up as much size as possible, but it might depend on the UI style. I could take a look at this later. Does it only apply to the list inputs that have "Remove" buttons or also horizontal list inputs with a fixed number of items?

For reference, this is how the XBee sensor physical pane looks for me:

settings-view

I have an idea for the `KeyboardInterrupt` that I will work out on another branch. It is unrelated to the (new) test that it fails on, since they have been passing all the time so far. My conjecture is that it is caused by some other test that starts a thread that is not deactivated in time, causing it to interrupt the main thread at a much later time.

**Comment by timvandermeij** [comment]
I'll push a fix for that soon.

I mean the input fields for the "sensors" setting, i.e., the ones with a "Remove" button. Other input fields are fine. Below is a screenshot of how it looks for me. Notice the small text fields that have a "Remove" button. Apparently this differs per OS, because I also have text in the buttons and some labels are cut off. Perhaps we can force the input boxes to fill the width in code, instead of letting Qt decide?

screenshot_20160326_194832

I'll also take a look at the other PR.

**Comment by timvandermeij** [comment]
Hm, it seems like some labels are also cut off. We need something to extend widgets to the full width.

**Comment by lhelwerd** [comment]
My guess is it depends on the window manager (i.e., Windows, Mac, or Gnome, Xfce, KDE). I might install KDE just for testing this, but if you can find a fix then that could work too. There are all kinds of ways to persuade Qt to use a certain width. Perhaps the first thing you can look at is what different kinds of calls to `sub_widget.setSizePolicy` in `ListFormWidget._add_to_list` would do. See [the list of size policy C++ enums](http://doc.qt.io/qt-5/qsizepolicy.html#Policy-enum).

**Comment by timvandermeij** [comment]
Sound good. I'll first check the other PR and then work in this some more.

**Comment by timvandermeij** [comment]
The commit above resolves all the issues I came across during testing. Could you let me know if it still works for you too? If so, I can review and merge this tomorrow.

**Comment by timvandermeij** [comment]
I have found two issues:
- In the settings view, go to "XBee sensor (physical)" and remove one of the sensor lines. Click Save and notice that all is fine in the JSON file. Close the application, open the application again, go to the settings view, go to "XBee sensor (physical)" again and notice that there are still three input boxes instead of two. This causes problems when re-clicking Save because a `null` entry will be added. I think somehow the number of sensors is still used from the defaults file instead of using the overridden changes in `settings.json`.
- Values that should be empty strings are saved as `null` entries. For instance, go to "XBee sensor (physical)" and immediately press Save. Notice that the `port` setting is `null`, where is should be an empty string.

Could you look into this? I'm pushed another fix I just made.

**Comment by lhelwerd** [comment]
I know why these issues appear and have an idea of how to fix them. However, I currently have some other things to put my mind towards. I will probably look at it tonight. Otherwise, here are some hints to the root causes:
- There is an `izip_longest` in the list view causing this, it should probably be reworked to  just looping for at must the value's length instead of the default.
- The null values are from an if statement in the text widget's `get_value` method, and is needed for the scenefile setting which does default to null. Perhaps we should make this depend on whether it is not marked as required. Or you can make the port default to null as well.

**Comment by timvandermeij** [comment]
Nice work! I'll create some follow-up patches for some things I found during review, though it's nothing major.

**Pull request merged**
