### PR TITLE
Remove unused imports/installations/files, implement the test runner in Python and introduce ThreadableTestCase

### PR DESCRIPTION
**Pull request by timvandermeij**
With this patch, Travis is able to catch unused imports before we push commits to the master branch. This, combined with the introduction of `ThreadableTestCase` to properly destroy all spawned threads, should also resolve the intermittent issues we experienced on Travis.

### CODE REVIEW

**Comment by lhelwerd** [comment]
- The patch itself looks great to me. It's a good idea to clean up this every once in a while, given that moved code and changes to callers or inheritances often changes which modules we need and which we no longer need.
- The scripts in `trajectory/` can be removed since they were only really there for reference material. Pretty much all the useful functionality is already inside the mission environment.
- Perhaps we can write our own script that uses the `importchecker` module, filters the `__package__` import, prints the unused imports and gives an appropriate exit code?

**Comment by timvandermeij** [comment]
Thank you. I'll try to make such a script as it's quite useful to catch unused imports before we push a commit to the master branch. I'll also look into those segmentation faults for Travis as they still occur (albeit intermittently)...

**Comment by lhelwerd** [comment]
With the new test runner, the segmentation fault seems to be replaced by the following: `Fatal Python error: PyImport_GetModuleDict: no module dictionary!` After a quick [Google search](http://stackoverflow.com/questions/17679715/fatal-python-error-pyimport-getmoduledict-no-module-dictionary), it seems this might be related to threads that are not deactivated before the main thread is killed. There might be a test using a `Thread_Manager` or `Threadable` object that is activated but never deactivated at `tearDown`.

We should probably fix this with a similar solution to the Settings caching problem, namely create a `ThreadableTestCase` that calls `deactivate` or `destroy` in its `tearDown` method. We can then use that for any tests that use such objects.

**Comment by timvandermeij** [comment]
Sounds like a good plan to me, I'll look into that. Note that the module error is also intermittent.

**Comment by lhelwerd** [comment]
For the thread tests:
- Every test that uses `Environment.setup` also creates a thread manager, obtainable via `self.environment.thread_manager`.
- Perhaps check whether a `thread_manager` member variable exists in `ThreadableTestCase`, before calling `destroy` on it.
- Should the `TestCoreThreadManager` test class also inherit from `ThreadableTestCase`?

**Comment by timvandermeij** [comment]
Thank you for the tips! They have all been addressed. The tests are now consistently green after the `ThreadableTestCase` was added to the XBee tests, so I think it should be fine now. Could you review this PR again and merge if you think it's good to go?

**Comment by lhelwerd** [comment]
Looks good, the tests indeed seem to have settled. All possible sources of stale threads should now be handled. Thanks for the doing the heavy lifting in this cleanup round.

**Pull request merged**
